services:
  web:
    environment:
      - REDISIP=redis
      - PORT=8050
    build: .
    ports:
      - "8000:8050"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
  redis:
    image: "redis:alpine"